# Generated by Django 4.1.5 on 2023-01-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mass_evictions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpatialRefSys',
        ),
        migrations.AlterModelOptions(
            name='attorneys',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='defendants',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='docket',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='filings',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='judgments',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='plaintiffs',
            options={'managed': True},
        ),
    ]
