# Generated by Django 4.1.5 on 2023-02-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mass_evictions', '0007_filings_def_attorney_filings_ptf_attorney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filings',
            name='def_bar_str',
        ),
        migrations.RemoveField(
            model_name='filings',
            name='ptf_bar_str',
        ),
    ]
