# Generated by Django 4.1.5 on 2024-02-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_evictions', '0008_remove_filings_def_bar_str_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('zip', models.TextField(blank=True, null=True)),
                ('add1', models.TextField(blank=True, null=True)),
                ('add2', models.TextField(blank=True, null=True)),
                ('match_type', models.TextField(blank=True, null=True)),
                ('geocoder', models.TextField(blank=True, null=True)),
                ('geometry', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaCorp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('roles', models.ManyToManyField(to='mass_evictions.role')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('addresses', models.ManyToManyField(to='mass_evictions.address')),
                ('people', models.ManyToManyField(to='mass_evictions.person')),
            ],
        ),
    ]
