# Generated by Django 4.1.5 on 2024-02-23 21:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            """
ALTER TABLE defendants
ADD COLUMN id SERIAL PRIMARY KEY; 

ALTER TABLE docket
ADD COLUMN id SERIAL PRIMARY KEY; 

ALTER TABLE events
ADD COLUMN id SERIAL PRIMARY KEY; 

ALTER TABLE filings
ADD COLUMN id SERIAL PRIMARY KEY; 

ALTER TABLE judgments
ADD COLUMN id SERIAL PRIMARY KEY; 

ALTER TABLE plaintiffs
ADD COLUMN id SERIAL PRIMARY KEY; 

"""
        ),
        migrations.CreateModel(
            name="Attorney",
            fields=[
                (
                    "bar",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("add1", models.CharField(blank=True, max_length=100, null=True)),
                ("add2", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zip", models.CharField(blank=True, max_length=20, null=True)),
                ("office", models.CharField(blank=True, max_length=150, null=True)),
                ("add_p", models.CharField(blank=True, max_length=500, null=True)),
                ("match_type", models.CharField(blank=True, max_length=50, null=True)),
                ("geocoder", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "attorneys",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DocketMeta",
            fields=[
                (
                    "docket",
                    models.TextField(db_index=True, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "docketmeta",
            },
        ),
        migrations.CreateModel(
            name="DocketOrphan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("docket", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "originator_model",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "docketorphans",
            },
        ),
        migrations.CreateModel(
            name="Filing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(blank=True, max_length=200, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("zip", models.CharField(blank=True, max_length=20, null=True)),
                ("case_type", models.CharField(blank=True, max_length=50, null=True)),
                ("file_date", models.DateField(blank=True, null=True)),
                ("case_status", models.CharField(blank=True, max_length=20, null=True)),
                ("close_date", models.DateField(blank=True, null=True)),
                ("dispo", models.TextField(blank=True, null=True)),
                ("dispo_date", models.DateField(blank=True, null=True)),
                ("district", models.TextField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("add1", models.CharField(blank=True, max_length=100, null=True)),
                ("add2", models.CharField(blank=True, max_length=100, null=True)),
                ("add_p", models.TextField(blank=True, null=True)),
                ("match_type", models.CharField(blank=True, max_length=50, null=True)),
                ("geocoder", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "def_attorney",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="filing_defendant_attorney",
                        to="who_owns.attorney",
                    ),
                ),
                (
                    "docket",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="filing_docket",
                        to="who_owns.docketmeta",
                    ),
                ),
                (
                    "ptf_attorney",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="filing_plaintiff_attorney",
                        to="who_owns.attorney",
                    ),
                ),
            ],
            options={
                "db_table": "filings",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Plaintiff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "docket",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="plaintiff_docket",
                        to="who_owns.docketmeta",
                    ),
                ),
            ],
            options={
                "db_table": "plaintiffs",
                "managed": True,
                "unique_together": {("docket", "name")},
            },
        ),
        migrations.CreateModel(
            name="Judgment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("method", models.TextField(blank=True, max_length=50, null=True)),
                (
                    "for_field",
                    models.CharField(
                        blank=True, db_column="for", max_length=200, null=True
                    ),
                ),
                ("against", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "docket",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="judgment_docket",
                        to="who_owns.docketmeta",
                    ),
                ),
            ],
            options={
                "db_table": "judgments",
                "managed": True,
                "unique_together": {
                    ("docket", "date", "type", "method", "for_field", "against")
                },
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("session", models.CharField(blank=True, max_length=70, null=True)),
                ("locality", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
                ("type", models.CharField(blank=True, max_length=20, null=True)),
                ("result", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "docket",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="event_docket",
                        to="who_owns.docketmeta",
                    ),
                ),
            ],
            options={
                "db_table": "events",
                "managed": True,
                "unique_together": {
                    (
                        "docket",
                        "date",
                        "locality",
                        "location",
                        "result",
                        "session",
                        "type",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="Docket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("text", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "docket",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="docket_meta",
                        to="who_owns.docketmeta",
                    ),
                ),
            ],
            options={
                "db_table": "docket",
                "managed": True,
                "unique_together": {("docket", "date", "text")},
            },
        ),
        migrations.CreateModel(
            name="Defendant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "docket",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="defendant_docket",
                        to="who_owns.docketmeta",
                    ),
                ),
            ],
            options={
                "db_table": "defendants",
                "managed": True,
                "unique_together": {("docket", "name")},
            },
        ),
    ]
