# Generated by Django 4.1.5 on 2024-08-16 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('who_owns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, unique=True)),
            ],
            options={
                'db_table': 'company_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EvictorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandlordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='judgment',
            name='atty_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='court_costs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='damage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='filing_fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='punitive',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('roles', models.ManyToManyField(to='who_owns.role')),
            ],
        ),
        
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='who_owns.person')),
            ],
        ),
        migrations.AddField(
            model_name='attorney',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='who_owns.person'),
        ),
        migrations.AddField(
            model_name='judgment',
            name='presiding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='who_owns.judge'),
        ),
        
    ]
