# Generated by Django 4.1.5 on 2024-06-14 16:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("who_owns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyCorps",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("entityname", models.CharField(blank=True, max_length=250, null=True)),
                ("label", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "group_network",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "corps",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LegacyEdges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_link", models.CharField(max_length=100, null=True)),
                ("id_corp", models.CharField(max_length=100, null=True)),
                ("relation", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "edges",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LegacyInds",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "fullname_simp",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "address_simp",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "name_address_simp",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("label", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "group_network",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "inds",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LegacyOwners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prop_id", models.CharField(blank=True, max_length=100, null=True)),
                ("loc_id", models.TextField(blank=True, null=True)),
                ("fy", models.IntegerField(null=True)),
                ("use_code", models.CharField(max_length=20)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("owner1", models.CharField(blank=True, max_length=500, null=True)),
                ("own_addr", models.CharField(max_length=200, null=True)),
                ("own_city", models.CharField(blank=True, max_length=50, null=True)),
                ("own_state", models.CharField(blank=True, max_length=50, null=True)),
                ("own_zip", models.CharField(blank=True, max_length=20, null=True)),
                ("zip", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "name_address",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("group", models.CharField(blank=True, max_length=100, null=True)),
                ("id_corp", models.CharField(blank=True, max_length=50, null=True)),
                ("count", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "owners",
                "managed": True,
            },
        ),
    ]
