# Generated by Django 4.1.5 on 2024-06-04 19:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('who_owns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('add1', models.CharField(blank=True, max_length=100, null=True)),
                ('add2', models.CharField(blank=True, max_length=100, null=True)),
                ('match_type', models.CharField(blank=True, max_length=50, null=True)),
                ('geocoder', models.CharField(blank=True, max_length=20, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='MetaCorp',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='judgment',
            name='atty_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='court_costs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='damage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='filing_fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='punitive',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('roles', models.ManyToManyField(to='who_owns.role')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('addresses', models.ManyToManyField(to='who_owns.address')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='who_owns.person')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('cluster', models.CharField(blank=True, max_length=100, null=True)),
                ('addresses', models.ManyToManyField(to='who_owns.address')),
                ('metacorp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='who_owns.metacorp')),
                ('people', models.ManyToManyField(to='who_owns.person')),
            ],
        ),
        migrations.AddField(
            model_name='attorney',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='who_owns.person'),
        ),
        migrations.AddField(
            model_name='judgment',
            name='presiding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='who_owns.judge'),
        ),
        migrations.AddField(
            model_name='plaintiff',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='who_owns.institution'),
        ),
        migrations.AddField(
            model_name='plaintiff',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='who_owns.person'),
        ),
    ]
