# Generated by Django 4.1.5 on 2024-10-30 16:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('who_owns', '0003_address_blockgroup_metacorp_municipality_parcel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelpoint',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=2249),
        ),
    ]
