# Generated by Django 4.1.5 on 2024-10-30 16:54

from django.db import migrations
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('who_owns', '0004_alter_parcelpoint_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelpoint',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parcelpoint',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
