# Generated by Django 4.1.5 on 2024-10-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('who_owns', '0005_rename_latitude_parcelpoint_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcelpoint',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='parcelpoint',
            old_name='longitude',
            new_name='lng',
        ),
    ]
