ALTER TABLE attorneys
ADD COLUMN id SERIAL PRIMARY KEY; 

ALTER TABLE defendants
ADD COLUMN id SERIAL PRIMARY KEY; 

ALTER TABLE docket
ADD COLUMN id SERIAL PRIMARY KEY; 

ALTER TABLE events
ADD COLUMN id SERIAL PRIMARY KEY; 

ALTER TABLE filings
ADD COLUMN id SERIAL PRIMARY KEY; 

ALTER TABLE judgments
ADD COLUMN id SERIAL PRIMARY KEY; 

ALTER TABLE plaintiffs
ADD COLUMN id SERIAL PRIMARY KEY; 
