# Generated by Django 4.1.5 on 2024-10-31 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('who_owns_mass', '0003_alter_address_muni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcelpoint',
            old_name='muni_id',
            new_name='muni',
        ),
    ]
