# Generated by Django 4.1.5 on 2024-10-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('who_owns_mass', '0004_rename_muni_id_parcelpoint_muni'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='inst',
            field=models.BooleanField(default=False, help_text='Institutional officer. If TRUE, we flagged the owner as institutional using keywords unlikely to be identified with individuals.'),
        ),
    ]
