# Generated by Django 4.1.5 on 2024-10-31 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('who_owns_mass', '0005_officer_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='who_owns_mass.company'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='metacorp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='who_owns_mass.metacorp'),
        ),
    ]
