# Generated by Django 4.1.5 on 2024-10-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('who_owns_mass', '0007_rename_muni_id_site_muni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetoowner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
