# Generated by Django 4.1.5 on 2024-10-31 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('who_owns_mass', '0008_alter_sitetoowner_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfficerRoles',
            new_name='OfficerToRole',
        ),
        migrations.AlterField(
            model_name='owner',
            name='metacorp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owners', to='who_owns_mass.metacorp'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='site',
            field=models.ManyToManyField(blank=True, related_name='owners', through='who_owns_mass.SiteToOwner', to='who_owns_mass.site'),
        ),
        migrations.AlterField(
            model_name='sitetoowner',
            name='owner',
            field=models.ForeignKey(help_text='Identifier of owner.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner_from_site', to='who_owns_mass.owner'),
        ),
        migrations.AlterField(
            model_name='sitetoowner',
            name='site',
            field=models.ForeignKey(help_text='Identifier of property.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='site_from_owner', to='who_owns_mass.site'),
        ),
    ]
